"use client";
import { useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { cloudError,roleLabels,type TeamRole } from '@/lib/cloud-book';
type Member={user_id:string;role:TeamRole;display_name:string};
type Invite={id:string;email:string;role:TeamRole;expires_at:string;used_at:string|null;revoked_at:string|null};
export function TeamAdmin({teamId,onChanged}:{teamId:string;onChanged:()=>void}) {
  const [members,setMembers]=useState<Member[]>([]);const [invites,setInvites]=useState<Invite[]>([]);const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [generation,setGeneration]=useState(0);
  useEffect(()=>{let live=true;Promise.all([supabase!.from('score_memberships').select('user_id,role,display_name').eq('team_id',teamId),supabase!.from('score_invites').select('id,email,role,expires_at,used_at,revoked_at').eq('team_id',teamId)]).then(([m,i])=>{if(!live)return;if(m.error||i.error){setError(cloudError(m.error??i.error));return;}setMembers(m.data as Member[]);setInvites(i.data as Invite[]);});return()=>{live=false;};},[teamId,generation]);
  const change=async(fn:()=>PromiseLike<{error:unknown}>)=>{if(busy)return;setBusy(true);setError('');try{const result=await fn();if(result.error)throw result.error;setGeneration(n=>n+1);onChanged();}catch(e){setError(cloudError(e));}finally{setBusy(false);}};
  return <details data-account-panel className="rounded-card border border-line bg-surface p-4"><summary className="cursor-pointer font-bold">チームへの招待・権限管理</summary>
    <form className="my-4 space-y-3" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);await change(async()=>{const result=await supabase!.rpc('score_create_invite',{p_team:teamId,p_email:String(data.get('email')),p_role:String(data.get('role'))});if(!result.error)setToken(result.data);return result;});}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-[1fr_130px_auto]">
      <label>招待先メール<input type="email" name="email" required maxLength={254} className="block min-h-11 w-full rounded-control border border-line px-3"/></label><label>権限<select name="role" defaultValue="viewer" className="block min-h-11 w-full rounded-control border border-line"><option value="viewer">閲覧者</option><option value="editor">記録者</option></select></label><button className="min-h-11 rounded-control bg-primary px-3 text-white">招待コードを作成</button>
    </fieldset></form>
    {token?<div role="status" className="my-3 space-y-2 rounded-control bg-sunken p-3"><p>招待先の方へこのコードを渡してください。有効期限は7日、1回だけ使えます。メールは自動送信しません。</p><textarea aria-label="招待コード" readOnly value={token} className="w-full break-all rounded border border-line p-2"/><button onClick={async()=>{try{await navigator.clipboard.writeText(token);}catch{setError('コードを選択してコピーしてください。');}}} className="min-h-11 underline">コードをコピー</button></div>:null}
    <h3 className="font-bold">参加者</h3><p className="text-xs text-muted">管理者は招待・権限変更、記録者は入力・編集、閲覧者は確認とバックアップができます。</p>
    {members.map(member=><form key={member.user_id} className="mt-2 flex flex-wrap items-center gap-2" onSubmit={e=>{e.preventDefault();const role=String(new FormData(e.currentTarget).get('role'));void change(()=>supabase!.rpc('score_set_role',{p_team:teamId,p_user:member.user_id,p_role:role}));}}><span className="min-w-0 flex-1 break-words">{member.display_name}</span><select aria-label={`${member.display_name}の権限`} name="role" defaultValue={member.role} disabled={busy} className="min-h-11 rounded border border-line">{Object.entries(roleLabels).map(([role,label])=><option key={role} value={role}>{label}</option>)}<option value="remove">参加を解除</option></select><button disabled={busy} className="min-h-11 px-3 underline">変更</button></form>)}
    <h3 className="mt-4 font-bold">発行した招待</h3>{invites.map(invite=><div key={invite.id} className="mt-2 flex flex-wrap items-center gap-2 text-sm"><span className="min-w-0 flex-1 break-all">{invite.email}・{roleLabels[invite.role]}・{invite.used_at?'参加済み':invite.revoked_at?'無効化済み':new Date(invite.expires_at)<new Date()?'期限切れ':'待機中'}</span>{!invite.used_at&&!invite.revoked_at?<button disabled={busy} className="min-h-11 underline" onClick={()=>void change(()=>supabase!.rpc('score_revoke_invite',{p_team:teamId,p_id:invite.id}))}>招待を無効にする</button>:null}</div>)}
    {error?<p role="alert" className="mt-3 text-action">{error}</p>:null}
  </details>;
}
